### PR TITLE
Handle Scala 3 enum & enum value

### LINKED ISSUE #359: ScalaCaseObjectSerializer fails to deserialize Scala 3 enum cases — NoSuchFieldException: MODULE$
## Summary

A case class containing a Scala 3 `enum` field fails at runtime during Flink deserialization, even though `deriveTypeInformation` compiles successfully. The root cause is `ScalaCaseObjectSerializer` using `clazz.getField("MODULE$")` which doesn't exist for Scala 3 enum cases.

## Reproduction

```scala
enum FailureCategory:
  case MISSING_KEY, PARSE_ERROR, UNKNOWN

case class FailureEvent(
    step: String,
    category: FailureCategory
)

object FailureEvent:
  given TypeInformation[FailureEvent] = deriveTypeInformation
```

When `FailureEvent` is serialized across a Flink network boundary (e.g. after `.union()` or a rebalance), deserialization crashes with:

```
java.lang.IllegalArgumentException: wrong number of arguments: 1 expected: 2
  at org.apache.flinkx.api.serializer.ConstructorCompat.lookupConstructor$$anonfun$1
```

The root cause is a `NoSuchFieldException` on `MODULE$` inside `ScalaCaseObjectSerializer`, which is silently caught by `CaseClassSerializer.deserializeFromSource` and surfaces as a field-count mismatch.

## Root cause

`CoproductSerializer` delegates each enum case to `ScalaCaseObjectSerializer`. In `ScalaCaseObjectSerializer.scala` lines 14 and 18-19:

```scala
override def createInstance(): T =
  clazz.getField("MODULE$").get(null).asInstanceOf[T]

override def deserialize(source: DataInputView): T =
  clazz.getField("MODULE$").get(null).asInstanceOf[T]
```

This assumes each sealed subtype is a Scala 2-style `case object` with a `MODULE$` static field. **Scala 3 simple enum cases do not have this field.** They compile to instances stored in the enum companion, not as separate classes with `MODULE$`:

```java
// Scala 2 case object - separate class with MODULE$
class FailureCategory$PARSE_ERROR$ {
  public static final MODULE$ = new FailureCategory$PARSE_ERROR$();
}

// Scala 3 enum case - no separate class, no MODULE$
class FailureCategory {
  public static final FailureCategory PARSE_ERROR = new FailureCategory("PARSE_ERROR", 2);
}
```

## How it surfaces

1. `deriveTypeInformation` compiles fine — Magnolia derives a `CoproductSerializer` for the enum and a `ScalaCaseObjectSerializer` per case.
2. Flink serialization writes the enum correctly (it only needs the ordinal byte + the serializer's `serialize()` which is a no-op for object serializers).
3. On deserialization, `ScalaCaseObjectSerializer.deserialize()` calls `clazz.getField("MODULE$")` which throws `NoSuchFieldException`.
4. `CaseClassSerializer.deserializeFromSource` catches this via `Try(fieldSerializers(i).deserialize(source))`, sets `fieldFound = false`, and exits the loop early.
5. `createInstance(fields.filter(_ != null))` is called with fewer arguments than the constructor expects.
6. The error surfaces as `IllegalArgumentException: wrong number of arguments`.

## Workaround

Replace the Scala 3 `enum` with a `sealed trait` + `case object`s:

```scala
sealed trait FailureCategory extends Product with Serializable
object FailureCategory:
  case object MISSING_KEY extends FailureCategory
  case object PARSE_ERROR extends FailureCategory
  case object UNKNOWN extends FailureCategory
```

Each `case object` compiles to a JVM class with `MODULE$`, which `ScalaCaseObjectSerializer` can find.

## Environment

- flink-scala-api version: `1.20.0_1.2.4` (but the code is unchanged in 2.2.1)
- Scala: 3.x
- Flink: 1.20.x

### PR DESCRIPTION
**Pull request by arnaud-daroussin**
Hi @novakov-alexey, @kirksw
Here is my proposal to handle correctly Scala 3 enums and enum values and fix https://github.com/flink-extended/flink-scala-api/issues/359.

Enums (eg `FailureCategory`) are Sums like sealed traits and must be handled in `TypeInformationDerivation.split` but are significatively different to sealed trait to require a special handling:
- in sealed traits, subtypes can be identified by their class
- with enums, their subtypes (enum values) cannot be identified by their class because they all have the same class but by their enum value name.

Difference big enough to have to create a new `Scala3EnumSerializer` similar to `CoproductSerializer`.

Enum values (eg `case MISSING_KEY`) are Products like case objects and must be handled in `TypeInformationDerivation.join` but are also significatively different to case objects for the same reason, but also because enum values cannot be found the same way:
- case objects have a `MODULE$` static field which hold their singleton.
- singleton of enum value are in static fields in the companion object of their enum, named with their enum value name.

In a same way I had to create a specific `Scala3EnumValueSerializer` similar to `ScalaCaseObjectSerializer`.

In order to identify if the derived type is an enum, I added a `TypeTag.isEnum` method in our TypeTag macro which check if it has a `scala.reflect.Enum` trait, AND don't have parameters (more on that later).

I also managed to add a `TypeTag.companion` method returning its companion object ClassTag if it exists (it should be always the case for enums) to pass it to the `Scala3EnumValueSerializer`.

Macro syntax is such a pain! Feel free to improve what I've done. I don't know if it can be simplified, but it works as is.

Last thing is the possibility to declare enum values like case classes:
```
  enum Example {
    case Foo(a: String, b: Int)
    case Bar
  }
```
Here `Foo` is an enum value but also a regular case class except it cannot be instantiated by its constructor (expected for an enum value).

I think the best way to handle this case is to consider it as a case class and handle it with a `CaseClassSerializer`. That's why I added in `TypeTag.isEnum` the check "have NO parameters" to fallback to case class.

Because of the new constraint on the constructor, case classes has to be created using their `apply` method (changes in `ConstructorCompat`), but I don't see any drawback to do so.

@novakov-alexey, I'm taking holidays for 1 week, so if you have some adjustments to do, feel free to do it!

### CODE REVIEW

File: modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+  override def getCurrentOuterSnapshotVersion: Int = Scala3EnumSerializerSnapshot.CurrentVersion
+
+  override protected def getNestedSerializers(outerSerializer: Scala3EnumSerializer[T]): Array[TypeSerializer[_]] =
+    outerSerializer.enumValueSerializers
+
+  override protected def createOuterSerializerWithNestedSerializers(
+      nestedSerializers: Array[TypeSerializer[_]]
+  ): Scala3EnumSerializer[T] =
+    // Serializer created by snapshot is only used to deserialize: first parameter is useless
+    new Scala3EnumSerializer(Array.empty, nestedSerializers)
```
Comment (kirksw) [inline modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala]: I'm not sure this is true as it loses important state needed to reconstruct an equivalent serializer later, I made the below test which shows it can't be reconstructed. It then passes if the enumValueNames are passed as the first argument.

```
  it should "serialize an enum after restoring its serializer snapshot" in {
    val ti = summon[TypeInformation[Failure]]
    val restoredSerializer = restoreSerializerFromSnapshot(ti.createSerializer(serializerConfig))

    roundtrip(restoredSerializer, PARSE_ERROR)
  }
```

```
  def restoreSerializerFromSnapshot[T](ser: TypeSerializer[T]): TypeSerializer[T] = {
    val snapBytes = new ByteArrayOutputStream()
    TypeSerializerSnapshot.writeVersionedSnapshot(
      new DataOutputViewStreamWrapper(snapBytes),
      ser.snapshotConfiguration()
    )
    TypeSerializerSnapshot.readVersionedSnapshot[T](
      new DataInputViewStreamWrapper(new ByteArrayInputStream(snapBytes.toByteArray)),
      ser.getClass.getClassLoader
    ).restoreSerializer()
  }
```

File: modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+    if (index == NullMarkerByte) {
+      null.asInstanceOf[T]
+    } else {
+      val subtype = enumValueSerializers(index.toInt)
+      subtype.asInstanceOf[TypeSerializer[T]].deserialize(source)
+    }
+  }
+
+  override def copy(source: DataInputView, target: DataOutputView): Unit = {
+    val index   = source.readByte()
```
Comment (kirksw) [inline modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala:72]: since source can be NullMarkerByte I think we need to handle this case otherwise it's indexing on -128

**Review by kirksw — CHANGES_REQUESTED** [review]

File: modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala (hunk 1 above)
Comment (arnaud-daroussin) [reply modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala]: Based on my experience, it will work. I can't give pointers to Flink's internals right now, though. 

Beside, I think you are right, I should rely on public API, not on undocumented Flink behavior that may change in the future.

File: modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala (hunk 2 above)
Comment (arnaud-daroussin) [reply modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala:72]: Yes, it's a bug!

Tests should have spot it but they are not testing the serializers nullability, they should for enum but not for enum value.

File: modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala (hunk 1 above)
Comment (arnaud-daroussin) [reply modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala]: @kirksw it's fixed :smile:

File: modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala (hunk 2 above)
Comment (arnaud-daroussin) [reply modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/serializer/Scala3EnumSerializer.scala:72]: @kirksw it's fixed :smile:

**Comment by novakov-alexey** [comment]
@arnaud-daroussin , @kirksw thank you guys for your contribution!
